version: 2

project_name: comics-galore-library

# Skip building binaries for libraries
builds:
  - binary: ""
    goos: [ ]
    goarch: [ ]

archives:
  - format: tar.gz
    files:
      - "**/*.go"
      - "go.mod"
      - "go.sum"

release:
  github:
    owner: antidote-recognize0663
    name: comics-galore-library

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
